### ISSUE TITLE
gcl-print: error while accessing values

### ISSUE THREAD

**Issue by spinus** [rix0rrr/gcl#13]
I have example from tests:

```
x = {
  y = {
    z = 3;
  };
  q = {
    z = 4;
  };
};
```

I can do:

```
$ ./build/venv/bin/gcl-print file    
+- x
|  +- q
|  |  +- z => 4
|  +- y
|  |  +- z => 3


$ ./build/venv/bin/gcl-print file x
x
+- q
|  +- z => 4
+- y
|  +- z => 3


$ ./build/venv/bin/gcl-print file x.y
x.y
+- z => 3


```

but I cannot do

```
$ ./build/venv/bin/gcl-print file x.y.z
x.y.z
Traceback (most recent call last):
  File "./build/venv/bin/gcl-print", line 11, in <module>
    sys.exit(main())
  File "/home/spinus/build/venv/lib/python2.7/site-packages/gcl/printer.py", line 160, in main
    print_selectors(model, args.selectors, printer, lowercase=args.lowercase, errors_only=args.errors_only)
  File "/home/spinus/build/venv/lib/python2.7/site-packages/gcl/printer.py", line 129, in print_selectors
    printer(value, **kwargs)
  File "/home/spinus/build/venv/lib/python2.7/site-packages/gcl/printer.py", line 113, in pretty_print_model
    util.walk(model, PrettyPrintWalker(table, **kwargs))
  File "/home/spinus/build/venv/lib/python2.7/site-packages/gcl/util.py", line 99, in walk
    walker.visitScalar(path, value)
  File "/home/spinus/build/venv/lib/python2.7/site-packages/gcl/printer.py", line 101, in visitScalar
    if not self._printableKey(key_path[-1]):
IndexError: list index out of range
```

**Comment by rix0rrr** [comment]
Oh that's probably a silly mistake in the printer somewhere. Thanks for the catch!

**Comment by rix0rrr** [comment]
Fixed in the latest release.

**Comment by spinus** [comment]
Cheers!
