### ISSUE TITLE
gcl-print broken in python3

### ISSUE THREAD

**Issue by Dlougach** [rix0rrr/gcl#33]
```
$ gcl-print 
Traceback (most recent call last):
  File "/home/jacob/.local/bin/gcl-print", line 9, in <module>
    load_entry_point('gcl==0.6.10', 'console_scripts', 'gcl-print')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/jacob/.local/lib/python3.5/site-packages/gcl-0.6.10-py3.5.egg/gcl/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/home/jacob/.local/lib/python3.5/site-packages/gcl-0.6.10-py3.5.egg/gcl/ast.py", line 746
    print 'Loading %s took %.3f' % (file_ref, time.time() - start)

```

**Comment by blais** [comment]
A lib2to3 conversion works without a hitch on GCL.
```
python3 -m lib2to3 -w 
```
